In [5]:
from function import *
from model_trainer import TrainModel
import numpy as np
from model import *
from function import plot_info

BATCH_SIZE = 512
EPOCH = 100
LR = 0.01 # 5e-6
GAMMA = 0.95
STEP_SIZE = 20  # 每隔多少个 epoch 衰减一次学习率
DECAY = 1e-4
DEVICE = "cuda"
SEED = 42
ALPHA_LOSS = 1
GAMMA_LOSS = 3

hyperparameters = {
    "BATCH_SIZE": BATCH_SIZE,
    "EPOCH": EPOCH,
    "LEARNING_RATE": LR,
    "GAMMA": GAMMA,
    "STEP_SIZE": STEP_SIZE,
    "DECAY": DECAY,
    "device": DEVICE,
    "SEED": SEED,
    "ALPHA_LOSS": ALPHA_LOSS,
    "GAMMA_LOSS": GAMMA_LOSS
}

# 设置随机种子
np.random.seed(SEED)
torch.manual_seed(SEED)

for SAMPLE_METHOD in ["undersample"]:
    for model in [BiLSTM, BiLSTM_BN]:
        tensor_direction = f'E:\deeplearning\Zhongda\zyy_tensor.pth'
        train_dataloader, val_dataloader, test_dataloader = main_data_loader(tensor_direction, SAMPLE_METHOD, BATCH_SIZE)
        model_name = f"ZYY_{model.__name__}_model_{SAMPLE_METHOD}_FocalLoss_{EPOCH}_{LR}"
        loss_f = FocalLoss(ALPHA_LOSS, GAMMA_LOSS)
        trainer = TrainModel(model_name, model, hyperparameters, train_dataloader, val_dataloader,
                             criterion_class=loss_f, root_dir='ZYY', save_model_index=[21, 57])
        info = trainer.train()
        # trainer.save_model()
        # plot_info(info, model_name, root_dir='ZYY')

---------------------------------------Epoch: 1---------------------------------------
Epoch 1, Train Loss: 0.0769
整体验证集上的Loss: 0.10601055158998349
AUROC: 0.6569
Best threshold: 0.1145
AUPRC: 0.1318
Best threshold: 0.1524
auc
Confusion Matrix:
[[8605 3961]
 [ 402  486]]
Specificity: 0.6848
Sensitivity: 0.5473
Alarm Accuracy: 0.1093
Accuracy: 0.6757
混淆矩阵，未归一化
prc
Confusion Matrix:
[[11566  1000]
 [  661   227]]
Specificity: 0.9204
Sensitivity: 0.2556
Alarm Accuracy: 0.1850
Accuracy: 0.8765
混淆矩阵，未归一化
---------------------------------------Epoch: 2---------------------------------------
Epoch 2, Train Loss: 0.0764
整体验证集上的Loss: 0.14667340015308947
AUROC: 0.5629
Best threshold: 0.3877
AUPRC: 0.1145
Best threshold: 0.3969
auc
Confusion Matrix:
[[10668  1898]
 [  588   300]]
Specificity: 0.8490
Sensitivity: 0.3378
Alarm Accuracy: 0.1365
Accuracy: 0.8152
混淆矩阵，未归一化
prc
Confusion Matrix:
[[10904  1662]
 [  610   278]]
Specificity: 0.8677
Sensitivity: 0.3131
Alarm Accuracy: 0.1433
Accuracy: 0.831